### ISSUE TITLE
"I can't create directory "/run/user/1000/doc/[...]" if output directory is set as "Same as CUE file"

### ISSUE THREAD

**Issue by hellpe** [flathub/com.github.Flacon#14]
**Steps to reproduce**

- Using GNOME 3.36 on Arch Linux, launch Flacon
- Click on "Add disc"
- In the GTK file picker, select a cue file 
- Click on the three dots newt to the "Audio:" line and select an audio file
- In the "Result Files" block, leave the "Directory" line empty, so it is set up to "Same directory as CUE file"
- Click on "Convert"

**Result**

The following error message  is displayed: "I can't create directory "/run/user/1000/doc/[...]".  Operation not permitted". You have to set up an existing directory in order to convert files.

**Comment by Eonfge** [comment]
Can you tell me in which directory you have your .cue file?

Be default, Flacon can only access your ~/Music and ~/Downloads folder. This is to protect your privacy, as you shouldn't have random programs with full data access 'looking around'. 

If you want to give special access to a folder, you can do that using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) or by using the cli:

```
flatpak override --filesystem=/YOUR/LOCATION --user com.github.Flacon
```

Let me know if this fixes your issue

**Comment by hellpe** [comment]
My .cue file was indeed in a different folder. I understand the limitation, but I was puzzled by the lack of information about it on the app itself, which I guess stems from the fact that it is exclusive to the Flatpak version. Should I report it upstream?

Thanks a lot for your explanation, this closes the issue for me.

**Comment by Eonfge** [comment]
@SokoloffA There is a valid comment here.

Flacon loads a .cue file, and then scans for all items in the folder. This is a bit janky in Flatpak.

Really, it should load a folder and then scan for all .cue files in the directory tree.

**Comment by Eonfge** [comment]
Closing this issue. We enabled full ~/home access on request by @SokoloffA, and the application can now also access network shares through gvfs.
