### ISSUE TITLE
Flacon ignores font scaling in GNOME DE

### ISSUE THREAD

**Issue by monday15** [flathub/com.github.Flacon#2]
Hi! Thanks for packaging Flacon!

I have custom font scaling factor set in GNOME desktop environment, but Flacon ignores it. However, okular (also qt5 application installed via flathub) respects that setting and renders fonts correctly. I think font scaling factor is provided by something called qgnomeplatform.

**Comment by Eonfge** [comment]
@monday15 I'm sorry for missing your comment, I was not actively watching the issues. Apparently, becoming a maintainer does not make you auto notify.

I've updated to the latest version of KDE. This might fix it. Let me know and I can look into it further.
